name = "ai-article-summary-backend"
main = "src/index.ts"
compatibility_date = "2025-06-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ai-article-summary-db"
database_id = "9d8785eb-2e34-42ec-adac-3e7d910ef5a0"

# 定期実行のスケジュール設定（JSTで毎週月曜日午前7時に実行）
[triggers]
crons = ["0 22 * * 7"]

# CORS設定
[env.production.vars]
CORS_ORIGIN = "https://ai-article-summary.pages.dev"

[env.staging.vars]
CORS_ORIGIN = "https://staging-ai-article-summary.pages.dev"

[env.development.vars]
CORS_ORIGIN = "http://localhost:3000" 